#![allow(clippy::unnecessary_map_or)]

use std::collections::HashMap;
use std::fs;
use std::path::Path;

fn main() {
    embed_resource::compile("resources.rc", embed_resource::NONE);

    let icons_dir = Path::new("assets/icons");
    let out_dir = std::env::var("OUT_DIR").unwrap();
    let out_path = Path::new(&out_dir).join("icons_data.rs");

    let mut out = String::new();
    out.push_str("// Generated by build.rs - compact icon data\n");

    let mut entries = fs::read_dir(icons_dir)
        .expect("Failed to read icons dir")
        .filter_map(|e| e.ok())
        .filter(|e| e.path().extension().map_or(false, |ext| ext == "rgba"))
        .collect::<Vec<_>>();
    entries.sort_by_key(|e| e.file_name());

    for entry in &entries {
        let path = entry.path();
        let name = path.file_stem().unwrap().to_str().unwrap();
        let data = fs::read(&path).expect("Failed to read icon file");

        let compact = quantize_rgba(&data);
        write_compact_array(&mut out, name, &compact);
    }

    fs::write(&out_path, out).expect("Failed to write icons_data.rs");
}

fn quantize_rgba(rgba: &[u8]) -> Vec<u8> {
    let pixel_count = rgba.len() / 4;

    let mut color_map: HashMap<[u8; 4], u8> = HashMap::new();
    let mut palette: Vec<[u8; 4]> = Vec::new();
    let mut indices: Vec<u8> = Vec::with_capacity(pixel_count);

    for i in 0..pixel_count {
        let color = [rgba[i * 4], rgba[i * 4 + 1], rgba[i * 4 + 2], rgba[i * 4 + 3]];
        let idx = *color_map.entry(color).or_insert_with(|| {
            let idx = palette.len() as u8;
            palette.push(color);
            idx
        });
        indices.push(idx);
    }

    if palette.len() <= 256 {
        let mut compact = Vec::with_capacity(1 + 1 + palette.len() * 4 + pixel_count);
        compact.push(1u8);
        compact.push((palette.len() - 1) as u8);
        for color in &palette {
            compact.extend_from_slice(color);
        }
        compact.extend_from_slice(&indices);
        compact
    } else {
        let mut compact = Vec::with_capacity(1 + rgba.len());
        compact.push(0u8);
        compact.extend_from_slice(rgba);
        compact
    }
}

fn write_compact_array(out: &mut String, name: &str, data: &[u8]) {
    out.push_str(&format!("pub static ICON_{}: &[u8] = &[\n", name.to_uppercase()));
    for chunk in data.chunks(32) {
        out.push_str("    ");
        for (i, b) in chunk.iter().enumerate() {
            out.push_str(&format!("{:#04x}, ", b));
            if i == chunk.len() - 1 {
                out.push('\n');
            }
        }
    }
    out.push_str("];\n\n");
}
